env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  eslint no-console: "off",
  import/extensions: "off",
  no-await-in-loop: "off"
}
